server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: eureka-service
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  secret: a2V5LWlzLWEtc2VjcmV0LWZvci1obGQtand0LXNpZ25pbmctdHdvLWh1bmRyZWQtYml0cy1sb25nLXNlY3JldA==
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000
  issuer: ecommerce-app

otp:
  expiration-minutes: 5

logging:
  level:
    com.ecommerce.auth: DEBUG
