server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    hostname: eureka-service

  client:
    service-url:
      defaultZone: http://eureka-service/eureka/

logging:
  level:
    com.ecommerce.user: DEBUG
